"""
gazo フォルダ整理後のパスマッピング定義

旧構造から新構造へのマッピングを定義し、
既存コードの互換性を保ちながら新しいパス構造を使用します。
"""

# 旧パス -> 新パスのマッピング
GAZO_PATH_MAPPING = {
    # UI要素（旧keyフォルダ -> 新uiフォルダ）
    "key/ok.png": "ui/ok.png",
    "key/close.png": "ui/close.png", 
    "key/yes.png": "ui/yes.png",
    "key/no.png": "ui/no.png",
    "key/back.png": "ui/back.png",
    "key/retry.png": "ui/retry.png",
    "key/modoru.png": "ui/modoru.png",
    "key/kettei.png": "ui/kettei.png",
    "key/option.png": "ui/option.png",
    "key/settei.png": "ui/settei.png",
    "key/sound.png": "ui/sound.png",
    "key/off.png": "ui/off.png",
    "key/tama.png": "ui/tama.png",
    "key/tama2.png": "ui/tama2.png",
    "key/waku.png": "ui/waku.png",
    "key/search.png": "ui/search.png",
    "key/kensaku.png": "ui/kensaku.png",
    "key/friends.png": "ui/friends.png",
    "key/friends_no.png": "ui/friends_no.png",
    "key/friends_search.png": "ui/friends_search.png",
    "key/friendzumi.png": "ui/friendzumi.png",
    "key/doors1.png": "ui/doors1.png",
    "key/doors2.png": "ui/doors2.png",
    "key/doors_close.png": "ui/doors_close.png",
    "key/doors_ok.png": "ui/doors_ok.png",
    "key/doors_renzoku.png": "ui/doors_renzoku.png",
    "key/doors_syuke.png": "ui/doors_syuke.png",
    "key/doors_tobira1.png": "ui/doors_tobira1.png",
    "key/doors_tobira2.png": "ui/doors_tobira2.png",
    "key/doors_yes.png": "ui/doors_yes.png",
    "key/gand.png": "ui/gand.png",
    "key/gand_end.png": "ui/gand_end.png",
    "key/gand_ok.png": "ui/gand_ok.png",
    "key/gand_skip.png": "ui/gand_skip.png",
    "key/gand_syutsu.png": "ui/gand_syutsu.png",
    "key/gand_syutsu2.png": "ui/gand_syutsu2.png",
    
    # 元keyフォルダの重要UI要素
    "key/obuclear.png": "login/obuclear.png",
    "key/cale.png": "ui/cale.png",
    "key/cale_off.png": "ui/cale_off.png",
    "key/cale_on.png": "ui/cale_on.png",
    "key/st-recored.png": "ui/st-recored.png",
    
    # ログイン・ナビゲーション関連（旧key -> 新login）
    "key/zz_home.png": "login/zz_home.png",
    "key/zz_home2.png": "login/zz_home2.png", 
    "key/zz_lost.png": "login/zz_lost.png",
    "key/room.png": "login/room.png",
    "key/go_tittle.png": "login/go_tittle.png",
    "key/aikotoba.png": "login/aikotoba.png",
    "key/gplay.png": "login/gplay.png",
    "key/icon.png": "login/icon.png",
    
    # ガチャ関連（旧key -> 新gacha）
    "key/gacha.png": "gacha/gacha.png",
    "key/gacha_back.png": "gacha/gacha_back.png",
    "key/gacha_black.png": "gacha/gacha_black.png",
    "key/gacharu.png": "gacha/gacharu.png",
    "key/hitoridegacha.png": "gacha/hitoridegacha.png",
    "key/hoshi_tama.png": "gacha/hoshi_tama.png",
    "key/hoshi_tama2.png": "gacha/hoshi_tama2.png",
    "gacha/10ren.png": "gacha/10ren.png",
    "gacha/gacha_back.png": "gacha/gacha_back.png",
    "gacha/hoshi_yuka.png": "gacha/hoshi_yuka.png",
    "gacha/yuka.png": "gacha/yuka.png",
    
    # 星関連（旧hoshi -> 新gacha）
    "hoshi/01_hoshi_sentaku.png": "gacha/01_hoshi_sentaku.png",
    "hoshi/02_hoshi_icon.png": "gacha/02_hoshi_icon.png",
    "hoshi/03_hoshi_s.png": "gacha/03_hoshi_s.png", 
    "hoshi/04_yes.png": "gacha/04_yes.png",
    
    # クエスト関連（旧key -> 新quest）
    "key/quest.png": "quest/quest.png",
    "key/quest_c.png": "quest/quest_c.png",
    "key/normal_quest.png": "quest/normal_quest.png",
    "key/noma.png": "quest/noma.png",
    "key/noma1.png": "quest/noma1.png",
    "key/counter.png": "quest/counter.png",
    "key/obu_counter1.png": "quest/obu_counter1.png",
    "quest/battle.png": "quest/battle.png",
    "quest/chosen.png": "quest/chosen.png",
    "quest/chosen_ok.png": "quest/chosen_ok.png",
    "quest/counter.png": "quest/counter.png",
    "quest/start.png": "quest/start.png",
    "quest/que_end.png": "quest/que_end.png",
    "quest/que_ok.png": "quest/que_ok.png",
    "quest/que_yes.png": "quest/que_yes.png",
    "quest/que_yes2.png": "quest/que_yes2.png",
    "quest/event_obu.png": "quest/event_obu.png",
    "quest/event_pue1.png": "quest/event_pue1.png",
    "quest/event_pue2.png": "quest/event_pue2.png",
    "quest/event_pue3.png": "quest/event_pue3.png",
    "quest/eventblack.png": "quest/eventblack.png",
    "quest/kaifuku.png": "quest/kaifuku.png",
    "quest/pue_shohi.png": "quest/pue_shohi.png",
    "quest/pue_shohi2.png": "quest/pue_shohi2.png",
    "quest/shugo.png": "quest/shugo.png",
    "quest/shugo_que.png": "quest/shugo_que.png",
    "quest/shugo_que2.png": "quest/shugo_que2.png",
    
    # ミッション関連（旧key -> 新mission）
    "key/m_mission.png": "mission/m_mission.png",
    "key/m_mission_b.png": "mission/m_mission_b.png",
    "key/nm_mission.png": "mission/nm_mission.png",
    "key/nm_mission_b.png": "mission/nm_mission_b.png",
    "key/nm_missionfin.png": "mission/nm_missionfin.png",
    "key/nm_uke.png": "mission/nm_uke.png",
    "key/m_uke0.png": "mission/m_uke0.png",
    "key/m_uke5.png": "mission/m_uke5.png",
    "key/nm_kamika.png": "mission/nm_kamika.png",
    "key/m_10tai.png": "mission/m_10tai.png",
    "key/m_3tai.png": "mission/m_3tai.png",
    "key/m_4tai.png": "mission/m_4tai.png",
    "key/m_5tai.png": "mission/m_5tai.png",
    "key/m_6tai.png": "mission/m_6tai.png",
    "key/m_7tai.png": "mission/m_7tai.png",
    "key/m_8tai.png": "mission/m_8tai.png",
    "key/m_close.png": "mission/m_close.png",
    "key/m_mitatsu.png": "mission/m_mitatsu.png",
    "key/m_stjoho.png": "mission/m_stjoho.png",
    "key/m_tujo.png": "mission/m_tujo.png",
    "key/m_tujofin.png": "mission/m_tujofin.png",
    "key/m_tujofin2.png": "mission/m_tujofin2.png",
    "key/m_tokugacha.png": "mission/m_tokugacha.png",
    "mission/m_kakunin.png": "mission/m_kakunin.png",
    "mission/m_tassei.png": "mission/m_tassei.png",
    "mission/m_uke0.png": "mission/m_uke0.png",
    "mission/m_uke5.png": "mission/m_uke5.png",
    
    # メダル交換関連（旧key -> 新medal）
    "key/hikikae.png": "medal/hikikae.png",
    "key/hikikae1.png": "medal/hikikae1.png",
    "key/hikikae2.png": "medal/hikikae2.png",
    "key/hikikae_g.png": "medal/hikikae_g.png",
    "key/hikikae_p.png": "medal/hikikae_p.png",
    "key/medal1.png": "medal/medal1.png",
    "key/medal2.png": "medal/medal2.png",
    "key/medal_fusoku.png": "medal/medal_fusoku.png",
    
    # イベント関連（既存event -> 新event）
    "event/check.png": "event/check.png",
    "event/el.png": "event/el.png",
    "event/geki.png": "event/geki.png",
    "event/masa.png": "event/masa.png",
    "event/vani.png": "event/vani.png",
    "event/sel1.png": "event/sel1.png",
    "event/sel2.png": "event/sel2.png",
    "event/sel3.png": "event/sel3.png",
    "event/sel4.png": "event/sel4.png",
    "event/sel5.png": "event/sel5.png",
    "event/sel6.png": "event/sel6.png",
    "event/sel7.png": "event/sel7.png",
    "event/sel8.png": "event/sel8.png",
    "event/sel9.png": "event/sel9.png",
    "event/sel10.png": "event/sel10.png",
    "event/sel11.png": "event/sel11.png",
    "event/sel12.png": "event/sel12.png",
    "event/sel13.png": "event/sel13.png",
    "event/sel14.png": "event/sel14.png",
    "event/sel15.png": "event/sel15.png",
    "event/sel16.png": "event/sel16.png",
    "event/sel17.png": "event/sel17.png",
    "event/sel21.png": "event/sel21.png",
    "event/sel22.png": "event/sel22.png",
    "event/sel_A.png": "event/sel_A.png",
    
    # マクロ関連（既存macro -> 新macro）
    "macro/close.png": "macro/close.png",
    "macro/hasya_fin.png": "macro/hasya_fin.png",
    "macro/kaishi.png": "macro/kaishi.png",
    "macro/koushin.png": "macro/koushin.png",
    "macro/load.png": "macro/load.png",
    "macro/load09.png": "macro/load09.png",
    "macro/load10.png": "macro/load10.png",
    "macro/load2.png": "macro/load2.png",
    "macro/event.png": "macro/event.png.png",
    "macro/macro.png": "macro/macro.png",
    "macro/macro_fin.png": "macro/macro_fin.png",
    "macro/nox.png": "macro/nox.png",
    "macro/ok.png": "macro/ok.png",
    "macro/restart.png": "macro/restart.png",
    "macro/saikai1.png": "macro/saikai1.png",
    "macro/saikai2.png": "macro/saikai2.png",
    
    # 売却機能関連（旧del -> 新sell）
    "del/end.png": "sell/end.png",
    "del/hensei.png": "sell/hensei.png",
    "del/ikkatsu.png": "sell/ikkatsu.png",
    "del/jogen.png": "sell/jogen.png",
    "del/kakunin.png": "sell/kakunin.png",
    "del/l4.png": "sell/l4.png",
    "del/l4check.png": "sell/l4check.png",
    "del/l4checkzzz.png": "sell/l4checkzzz.png",
    "del/l5.png": "sell/l5.png",
    "del/l5check.png": "sell/l5check.png",
    "del/l5checkzzz.png": "sell/l5checkzzz.png",
    "del/off.png": "sell/off.png",
    "del/ok.png": "sell/ok.png",
    "del/ok2.png": "sell/ok2.png",
    "del/ok3.png": "sell/ok3.png",
    "del/pre.png": "sell/pre.png",
    "del/sentaku.png": "sell/sentaku.png",
    "del/sonota.png": "sell/sonota.png",
    "del/yes.png": "sell/yes.png",
    "del/yes2.png": "sell/yes2.png",
    "del/yes3.png": "sell/yes3.png",
    
    # アイコン関連（旧icon/mon -> 新icons）
    "icon/shugo1.png": "icons/shugo1.png",
    "icon/shugo2.png": "icons/shugo2.png",
    "icon/shugo3.png": "icons/shugo3.png",
    "icon/shugo4.png": "icons/shugo4.png",
    "icon/shugo5.png": "icons/shugo5.png",
    "icon/shugo6.png": "icons/shugo6.png",
    "icon/shugo7.png": "icons/shugo7.png",
    "icon/shugo8.png": "icons/shugo8.png",
    "mon/m1.png": "icons/m1.png",
    "mon/m2.png": "icons/m2.png",
    "mon/m3.png": "icons/m3.png",
    "mon/m4.png": "icons/m4.png",
    "mon/m5.png": "icons/m5.png",
    "mon/m6.png": "icons/m6.png",
    "mon/m7.png": "icons/m7.png",
    "mon/m8.png": "icons/m8.png",
    "mon/m9.png": "icons/m9.png",
    "mon/m10.png": "icons/m10.png",
    "mon/m11.png": "icons/m11.png",
    "mon/m12.png": "icons/m12.png",
    "mon/m13.png": "icons/m13.png",
    "mon/m14.png": "icons/m14.png",
    "mon/m15.png": "icons/m15.png",
    "mon/m16.png": "icons/m16.png",
    
    # その他のキー画像（旧key -> 適切なフォルダ）
    "key/monster.png": "ui/monster.png",
    "key/monbox.png": "ui/monbox.png",
    "key/sell.png": "ui/sell.png",
    "key/sell2.png": "ui/sell2.png",
    "key/name.png": "ui/name.png",
    "key/name_hen.png": "ui/name_hen.png",
    "key/name_ok.png": "ui/name_ok.png",
    "key/name_ok2.png": "ui/name_ok2.png",
    "key/nicname.png": "ui/nicname.png",
    "key/multi.png": "ui/multi.png",
    "key/solo.png": "ui/solo.png",
    "key/hitori.png": "ui/hitori.png",
    "key/minnato.png": "ui/minnato.png",
    "key/sanka.png": "ui/sanka.png",
    "key/bosyusuru.png": "ui/bosyusuru.png",
    "key/uketsuke.png": "ui/uketsuke.png",
    "key/uketoru.png": "ui/uketoru.png",
    "key/ichiran.png": "ui/ichiran.png",
    "key/narabi.png": "ui/narabi.png",
    "key/hyoujijun.png": "ui/hyoujijun.png",
    "key/chara_select.png": "ui/chara_select.png",
    "key/dekki_null.png": "ui/dekki_null.png",
    "key/dekki_null2.png": "ui/dekki_null2.png",
    "key/zokuse.png": "ui/zokuse.png",
    "key/fire.png": "ui/fire.png",
    "key/fire1.png": "ui/fire1.png",
    "key/fire3.png": "ui/fire3.png",
    "key/chu.png": "ui/chu.png",
    "key/chu2.png": "ui/chu2.png",
    "key/cale.png": "ui/cale.png",
    "key/cale_off.png": "ui/cale_off.png",
    "key/cale_on.png": "ui/cale_on.png",
    "key/new.png": "ui/new.png",
    "key/last.png": "ui/last.png",
    "key/seed.png": "ui/seed.png",
    "key/tiket.png": "ui/tiket.png",
    "key/tiket2.png": "ui/tiket2.png",
    "key/muryoorb.png": "ui/muryoorb.png",
    "key/obu.png": "ui/obu.png",
    "key/obu3.png": "ui/obu3.png",
    "key/obu3a.png": "ui/obu3a.png",
    "key/obuclear.png": "login/obuclear.png",
    "key/shohi20.png": "ui/shohi20.png",
    "key/shugo_box.png": "ui/shugo_box.png",
    "key/shugo_box2.png": "ui/shugo_box2.png",
    "key/shugo_ishi.png": "ui/shugo_ishi.png",
    "key/kyube.png": "ui/kyube.png",
    "key/kyube2.png": "ui/kyube2.png",
    "key/kyube_end.png": "ui/kyube_end.png",
    "key/kyukyoku.png": "ui/kyukyoku.png",
    "key/kyukyoku2.png": "ui/kyukyoku2.png",
    "key/tenshi_1.png": "ui/tenshi_1.png",
    "key/tenshi_2.png": "ui/tenshi_2.png",
    "key/tenshi_kaifu.png": "ui/tenshi_kaifu.png",
    "key/uijin.png": "ui/uijin.png",
    "key/uijin2.png": "ui/uijin2.png",
    "key/mishoji.png": "ui/mishoji.png",
    "key/sonota.png": "ui/sonota.png",
    "key/settei2.png": "ui/settei2.png",
    "key/backup.png": "ui/backup.png",
    "key/backup2.png": "ui/backup2.png",
    "key/data_yes.png": "ui/data_yes.png",
    "key/date_repear.png": "ui/date_repear.png",
    "key/op_end.png": "ui/op_end.png",
    "key/st-recored.png": "ui/st-recored.png",
    "key/close_mon.png": "ui/close_mon.png",
    "key/hasyafin1.png": "macro/hasyafin1.png",
    "key/hasyafin2.png": "macro/hasyafin2.png",
    "key/hasyafin3.png": "macro/hasyafin3.png",
    "key/hasyatou.png": "macro/hasyatou.png",
    "key/hasyatou0.png": "macro/hasyatou0.png",
    "key/hasyatou2.png": "macro/hasyatou2.png",
    "key/hasyatou3.png": "macro/hasyatou3.png",
    "key/hasyatou4.png": "macro/hasyatou4.png",
    "key/hasyatou5.png": "macro/hasyatou5.png",
    "key/hasyatou6.png": "macro/hasyatou6.png",
    "key/yes_bu.png": "ui/yes_bu.png",
    "key/yes_choice.png": "ui/yes_choice.png",
    "key/yes_choice2.png": "ui/yes_choice2.png",
    "key/yes_f.png": "ui/yes_f.png",
    "key/ok_2.png": "ui/ok_2.png",
    "key/ok_f.png": "ui/ok_f.png",
    "key/ok_f2.png": "ui/ok_f2.png",
    "key/bu_ok.png": "ui/bu_ok.png",
    "key/a_ok1.png": "ui/a_ok1.png",
    "key/a_ok2.png": "ui/a_ok2.png",
    
    # ログイン用画像（旧login -> 新login）
    "login/a_ok1.png": "login/a_ok1.png",
    "login/a_ok2.png": "login/a_ok2.png",
    "login/ato2.png": "login/ato2.png",
    "login/close.png": "login/close.png",
    "login/doui.png": "login/doui.png",
    "login/icon12.png": "login/icon12.png",
    "login/no.png": "login/no.png",
    "login/noretry.png": "login/noretry.png",
    "login/retry.png": "login/retry.png",
    
    # 新規登録関連（旧new -> 新login）
    "new/ID.png": "login/ID.png",
    "new/XFLAGID.png": "login/XFLAGID.png",
    "new/doui.png": "login/doui.png",
    "new/download.png": "login/download.png",
    "new/fri_x.png": "login/fri_x.png",
    "new/gacha_shu.png": "login/gacha_shu.png",
    "new/hikitsugi.png": "login/hikitsugi.png",
    "new/icon.png": "login/icon.png",
    "new/kochira.png": "login/kochira.png",
    "new/kyoka.png": "login/kyoka.png",
    "new/login.png": "login/login.png",
    "new/mail.png": "login/mail.png",
    "new/mail2.png": "login/mail2.png",
    "new/ok.png": "login/ok.png",
    "new/ok2.png": "login/ok2.png",
    "new/pass.png": "login/pass.png",
    "new/renkei.png": "login/renkei.png",
    "new/title.png": "login/title.png",
    "new/title_ju.png": "login/title_ju.png",
    "new/yes.png": "login/yes.png",
    "new/yes2.png": "login/yes2.png",
    
    # ガチャ・星・エンド関連の追加マッピング
    "hoshi/01_hoshi_sentaku.png": "gacha/01_hoshi_sentaku.png",
    "hoshi/02_hoshi_icon.png": "gacha/02_hoshi_icon.png", 
    "hoshi/03_hoshi_s.png": "gacha/03_hoshi_s.png",
    "hoshi/04_yes.png": "gacha/04_yes.png",
    "hoshi/tama.png": "gacha/tama.png",
    "hoshi/tama2.png": "gacha/tama2.png",
    "hoshi/hoshi_tama.png": "gacha/hoshi_tama.png",
    "hoshi/hoshi_tama2.png": "gacha/hoshi_tama2.png",
    "end/gacharu.png": "gacha/gacharu.png",
    "end/empty.png": "deprecated/end/empty.png",
    "end/shinshun_icon.png": "deprecated/end/shinshun_icon.png",
    "end/shinshun_zenshin.png": "deprecated/end/shinshun_zenshin.png",
    "end/syoji1.png": "deprecated/end/syoji1.png",
    "end/syoji2.png": "deprecated/end/syoji2.png",
    "key/tama.png": "gacha/tama.png",
    "key/tama2.png": "gacha/tama2.png",
    "key/hoshi_tama.png": "gacha/hoshi_tama.png",
    "key/hoshi_tama2.png": "gacha/hoshi_tama2.png",
    "key/gacha_back.png": "gacha/gacha_back.png",
    "key/gacha_black.png": "gacha/gacha_black.png",
    "key/gacha.png": "gacha/gacha.png",
}

def get_mapped_path(old_path: str) -> str:
    """
    旧パスを新パスにマッピングします。
    
    Args:
        old_path: 旧構造のパス（例: "key/ok.png"）
        
    Returns:
        新構造のパス（例: "ui/ok.png"）、マッピングが見つからない場合は元のパス
    """
    return GAZO_PATH_MAPPING.get(old_path, old_path)

def get_legacy_folder_mapping(folder: str) -> str:
    """
    旧フォルダ名を新フォルダ名にマッピングします。
    
    Args:
        folder: 旧フォルダ名（例: "key"）
        
    Returns:
        新フォルダ名（例: "ui"）、マッピングが見つからない場合は元のフォルダ名
    """
    folder_mapping = {
        "key": "ui",        # keyフォルダの大部分はuiへ
        "hoshi": "gacha",   # hoshiフォルダはgachaへ
        "icon": "icons",    # iconフォルダはiconsへ
        "mon": "icons",     # monフォルダはiconsへ
        "new": "login",     # newフォルダはloginへ
        "del": "sell",      # delフォルダはsellへ（売却機能用）
        "end": "deprecated", # endフォルダはdeprecatedへ
        "old": "deprecated", # oldフォルダはdeprecatedへ
    }
    return folder_mapping.get(folder, folder)
